parameters:
  media_storage_root: "%kernel.project_dir%/var/media"
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Aws\S3\S3Client:
    factory: ['Aws\S3\S3Client', "factory"]
    arguments:
      - version: "latest"
        region: "%env(AWS_REGION)%"
        endpoint: "%env(AWS_ENDPOINT)%"
        use_path_style_endpoint: true
        credentials:
          key: "%env(AWS_ACCESS_KEY_ID)%"
          secret: "%env(AWS_SECRET_ACCESS_KEY)%"

  App\Modules\Media\Application\Port\MediaStorageInterface:
    alias: App\Modules\Media\Infrastructure\Storage\S3MediaStorage

  App\Modules\Shared\Application\Port\RealtimePublisherInterface:
    alias: App\Modules\Shared\Infrastructure\Realtime\MessengerRealtimePublisher

  App\Modules\Shared\Application\Port\EmailSenderInterface:
      alias: App\Modules\Shared\Infrastructure\Mail\MessengerMailer

  App\:
    resource: "../src/"
