services:
  ###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80:80"
  ###< symfony/mercure-bundle ###

  s3:
    ports:
      - "9000:9000" # S3 API endpoint
      - "9001:9001" # Web console (UI)

